FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    lsb-release \
    ca-certificates \
    curl \
    python3 \
    python3-pip \
    man \
    bash-completion \
    git \
 && install -m 0755 -d /etc/apt/keyrings \
 && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
 && chmod a+r /etc/apt/keyrings/docker.asc \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" \
    > /etc/apt/sources.list.d/docker.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends docker-ce-cli \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* 

USER jenkins
RUN jenkins-plugin-cli --plugins \
    "trilead-api" \
    "ssh-slaves" \
    "ssh-credentials" \
    "credentials" \
    "docker-workflow" \
    "json-path-api" \
    "blueocean"